services:
  taskmanager:
    build:
      context: .
      dockerfile: TaskManager/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: taskmanager_postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: q123456
      POSTGRES_DB: taskmanager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d taskmanager"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
